# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tool/google_auth_migration.proto
# Protobuf Python Version: 5.29.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    4,
    '',
    'tool/google_auth_migration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n tool/google_auth_migration.proto\x12\x04tool\"\xd7\x01\n\x10MigrationPayload\x12+\n\x0eotp_parameters\x18\x01 \x03(\x0b\x32\x13.tool.OtpParameters\x12\x14\n\x07version\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x17\n\nbatch_size\x18\x03 \x01(\x05H\x01\x88\x01\x01\x12\x18\n\x0b\x62\x61tch_index\x18\x04 \x01(\x05H\x02\x88\x01\x01\x12\x15\n\x08\x62\x61tch_id\x18\x05 \x01(\x05H\x03\x88\x01\x01\x42\n\n\x08_versionB\r\n\x0b_batch_sizeB\x0e\n\x0c_batch_indexB\x0b\n\t_batch_id\"\xa1\x02\n\rOtpParameters\x12\x13\n\x06secret\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06issuer\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\'\n\talgorithm\x18\x04 \x01(\x0e\x32\x0f.tool.AlgorithmH\x03\x88\x01\x01\x12%\n\x06\x64igits\x18\x05 \x01(\x0e\x32\x10.tool.DigitCountH\x04\x88\x01\x01\x12 \n\x04type\x18\x06 \x01(\x0e\x32\r.tool.OtpTypeH\x05\x88\x01\x01\x12\x14\n\x07\x63ounter\x18\x07 \x01(\x03H\x06\x88\x01\x01\x42\t\n\x07_secretB\x07\n\x05_nameB\t\n\x07_issuerB\x0c\n\n_algorithmB\t\n\x07_digitsB\x07\n\x05_typeB\n\n\x08_counter*V\n\tAlgorithm\x12\x1e\n\x1a\x41LGORITHM_TYPE_UNSPECIFIED\x10\x00\x12\x08\n\x04SHA1\x10\x01\x12\n\n\x06SHA256\x10\x02\x12\n\n\x06SHA512\x10\x03\x12\x07\n\x03MD5\x10\x04*=\n\nDigitCount\x12\x1b\n\x17\x44IGIT_COUNT_UNSPECIFIED\x10\x00\x12\x07\n\x03SIX\x10\x01\x12\t\n\x05\x45IGHT\x10\x02*7\n\x07OtpType\x12\x18\n\x14OTP_TYPE_UNSPECIFIED\x10\x00\x12\x08\n\x04HOTP\x10\x01\x12\x08\n\x04TOTP\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tool.google_auth_migration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALGORITHM']._serialized_start=552
  _globals['_ALGORITHM']._serialized_end=638
  _globals['_DIGITCOUNT']._serialized_start=640
  _globals['_DIGITCOUNT']._serialized_end=701
  _globals['_OTPTYPE']._serialized_start=703
  _globals['_OTPTYPE']._serialized_end=758
  _globals['_MIGRATIONPAYLOAD']._serialized_start=43
  _globals['_MIGRATIONPAYLOAD']._serialized_end=258
  _globals['_OTPPARAMETERS']._serialized_start=261
  _globals['_OTPPARAMETERS']._serialized_end=550
# @@protoc_insertion_point(module_scope)
